name: CI-Github-actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x,20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (with retry, cached)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != '' }}
        uses: Wandalen/wretry.action@v1
        with:
          action: actions/setup-node@v4
          attempt_limit: 3
          attempt_delay: 10000
          with: |
            node-version: ${{ matrix.node-version }}
            cache: npm
      - name: Setup Node (with retry, no cache)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') == '' }}
        uses: Wandalen/wretry.action@v1
        with:
          action: actions/setup-node@v4
          attempt_limit: 3
          attempt_delay: 10000
          with: |
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies (ci)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json') != '' }}
        run: npm ci
      - name: Install dependencies (install)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json') == '' }}
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm run test --if-present